import type { Book } from './types'

export const MOCK_BOOKS: Book[] = [
  {
    id: '1',
    title: '채식주의자',
    author: '한강',
    cover_url: 'https://covers.openlibrary.org/b/id/15182525-L.jpg',
    status: 'completed',
    rating: 4.5,
    memo: '잔잔하지만 깊은 여운을 남기는 소설. 인간의 욕망과 폭력성, 그리고 그 속에서 조용히 저항하는 한 여성의 이야기가 오래도록 마음에 남는다. 한강 작가의 문체는 서늘하고도 아름답다.',
    started_at: '2026-03-01',
    finished_at: '2026-03-14',
    created_at: '2026-03-01',
  },
  {
    id: '2',
    title: '82년생 김지영',
    author: '조남주',
    cover_url: 'https://covers.openlibrary.org/b/id/9338903-L.jpg',
    status: 'completed',
    rating: 4,
    memo: '우리 사회의 구조적인 문제를 담담하게 서술한 소설. 특별한 사건이 없는 평범한 삶의 서사가 오히려 더 묵직하게 다가온다. 많은 것을 생각하게 만드는 책.',
    started_at: '2026-04-05',
    finished_at: '2026-04-12',
    created_at: '2026-04-05',
  },
  {
    id: '3',
    title: '아몬드',
    author: '손원평',
    cover_url: 'https://covers.openlibrary.org/b/isbn/9788936434267-L.jpg',
    status: 'completed',
    rating: 5,
    memo: '감정을 느끼지 못하는 소년의 성장 이야기. 읽으면서 오히려 나 자신의 감정에 대해 더 많이 생각하게 됐다. 올해 읽은 책 중 가장 인상 깊었던 작품.',
    started_at: '2026-05-01',
    finished_at: '2026-05-08',
    created_at: '2026-05-01',
  },
  {
    id: '4',
    title: '파친코',
    author: '이민진',
    cover_url: 'https://covers.openlibrary.org/b/id/8044605-L.jpg',
    status: 'reading',
    rating: 4,
    memo: '4세대에 걸친 재일 한국인 가족의 이야기. 방대한 서사지만 한 번 잡으면 손에서 내려놓기 어렵다. 역사와 개인의 삶이 어떻게 교차하는지 잘 보여준다.',
    started_at: '2026-07-01',
    finished_at: null,
    created_at: '2026-07-01',
  },
  {
    id: '5',
    title: '데미안',
    author: '헤르만 헤세',
    cover_url: 'https://covers.openlibrary.org/b/id/12569297-L.jpg',
    status: 'completed',
    rating: 4.5,
    memo: '청소년 때 읽었던 책을 다시 읽으니 완전히 다르게 다가온다. 자아를 찾아가는 여정에 대한 이야기가 나이에 따라 다른 의미로 읽힌다.',
    started_at: '2026-02-10',
    finished_at: '2026-02-18',
    created_at: '2026-02-10',
  },
  {
    id: '6',
    title: '어린 왕자',
    author: '앙투안 드 생텍쥐페리',
    cover_url: 'https://covers.openlibrary.org/b/id/10746692-L.jpg',
    status: 'completed',
    rating: 5,
    memo: '몇 번을 읽어도 새로운 의미를 발견하는 책. 짧지만 인생의 본질에 대한 깊은 통찰이 담겨 있다. 어른이 되어 읽으니 더 슬프고 아름답다.',
    started_at: '2026-06-20',
    finished_at: '2026-06-21',
    created_at: '2026-06-20',
  },
  {
    id: '7',
    title: '총, 균, 쇠',
    author: '재레드 다이아몬드',
    cover_url: 'https://covers.openlibrary.org/b/id/7884018-L.jpg',
    status: 'want_to_read',
    rating: 0,
    memo: '',
    started_at: null,
    finished_at: null,
    created_at: '2026-07-10',
  },
  {
    id: '8',
    title: '코스모스',
    author: '칼 세이건',
    cover_url: 'https://covers.openlibrary.org/b/id/8283901-L.jpg',
    status: 'want_to_read',
    rating: 0,
    memo: '',
    started_at: null,
    finished_at: null,
    created_at: '2026-07-15',
  },
]
